name: Update Index File

on:
  push:
    branches:
      - main  # You can change this to your default branch

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Ensure Node.js is installed for running a script

      - name: Get list of files from repository
        run: |
          # Get list of files in each folder
          echo "Fetching files from repository folders..."

          # 3D Models
          MODEL_FILES=$(ls  3d-models)
          IMAGE_FILES=$(ls  images)
          VIDEO_FILES=$(ls  videos)
          AUDIO_FILES=$(ls  audios)

          echo "Updating index.html..."

          # Build the list of files for each category first
          MODEL_LIST=$(echo $MODEL_FILES | sed 's/ /", "/g' | sed 's/^/"/' | sed 's/$/"/')
          IMAGE_LIST=$(echo $IMAGE_FILES | sed 's/ /", "/g' | sed 's/^/"/' | sed 's/$/"/')
          VIDEO_LIST=$(echo $VIDEO_FILES | sed 's/ /", "/g' | sed 's/^/"/' | sed 's/$/"/')
          AUDIO_LIST=$(echo $AUDIO_FILES | sed 's/ /", "/g' | sed 's/^/"/' | sed 's/$/"/')

          # Now build the full FILE_DATA string
          FILE_DATA="const fileData = {
            '3d-models': [$MODEL_LIST],
            'images': [$IMAGE_LIST],
            'videos': [$VIDEO_LIST],
            'audios': [$AUDIO_LIST]
          };"

          # Print FILE_DATA for debugging
          echo "FILE_DATA: $FILE_DATA"

          # Update the index.html file with the new fileData object
          sed -i 's|const fileData = {[^}]*};|'"$FILE_DATA"'|' ../index.html

          # Verify if index.html is updated correctly
          echo "Updated index.html:"
          cat ../index.html
          
      - name: Commit and push the changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git add ../index.html
          git commit -m "Auto-update fileData in index.html"
          git push
